export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAILURE = 'FETCH_CHARACTERS_FAILURE';

export const FETCH_CHARACTER_DETAIL = 'FETCH_CHARACTER_DETAIL';
export const FETCH_CHARACTER_DETAIL_SUCCESS = 'FETCH_CHARACTER_DETAIL_SUCCESS';
export const FETCH_CHARACTER_DETAIL_FAILURE = 'FETCH_CHARACTER_DETAIL_FAILURE';

export const FETCH_MORE_CHARACTERS = 'FETCH_MORE_CHARACTERS';
export const FETCH_MORE_CHARACTERS_SUCCESS = 'FETCH_MORE_CHARACTERS_SUCCESS';
export const FETCH_MORE_CHARACTERS_FAILURE = 'FETCH_MORE_CHARACTERS_FAILURE';
